# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_status', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default='M', max_length=1, null=True)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('about_me', models.TextField(null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='Father name')),
                ('mother_name', models.CharField(blank=True, max_length=255, verbose_name='Father name')),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile_images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user_settings.Profile')),
            ],
        ),
    ]
