# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_auto_20170427_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_profile_for',
            field=models.IntegerField(choices=[(0, b'Self'), (1, b'Son'), (2, b'Daughter'), (3, b'Relatives')], default=0, null=True),
        ),
    ]
