# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0006_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mother name'),
        ),
    ]
